### ISSUE TITLE
[Bug] Przypisanie nowego badania do złej wizyty

### ISSUE THREAD

**Issue by quepas** [dev3dbody/PhysioClient2#72]
Błąd zgłoszony przez pracowników kliniki. Nowe badanie (nr 15) automatycznie przypisało się do wizyty innego pacjenta sprzed 2 tygodni, która następnie się otworzyła jako "aktywna" wizyta. Możliwe zamieszanie przy ID wizyt? Możliwe, że bład został już naprawiony? (w klinice używają wersji https://github.com/dev3dbody/PhysioClient2/commit/ddde504093ce85186ea173f405848f21db046123).

![bug_physioclient2](https://user-images.githubusercontent.com/3787206/74614183-039d6b00-5116-11ea-94c5-93b95c4032be.png)

**Comment by jaaaco** [comment]
udało mi się zreprodukować problem, błąd był w warunkach filtrowania skanów pod wizytą: pod każdą wizytą pacjenta pojawiały się wszystkie skany, PR naprawia już ten problem
